version: '3.7'

# https://github.com/aerospike/aerospike-docker-swarm/blob/master/aerospike.yml
services:
  aerospikedb:
    image: aerospike/aerospike-server:latest
    networks:
      - aerospikenetwork
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    labels:
      com.aerospike.description: "This label is for all containers for the Aerospike service"
    volumes:
      - ./run/secrets/:/run/secrets/
    secrets:
      - source: conffile
        target: aerospike.conf
        mode: 0440
    ports:
      - "3000:3000"

#  meshworker:
#    image: aerospike/aerospike-tools:latest
#    networks:
#      - aerospikenetwork
#    depends_on:
#      - aerospikedb
#    entrypoint:
#      - /run/secrets/discovery
#      - "--servicename"
#      - aerospikedb
#      - "-i"
#      - "5"
#      - "-v"
#    secrets:
#      - source: discoveryfile
#        target: discovery
#        mode: 0750

networks:
  aerospikenetwork:
    driver: overlay
    attachable: true

secrets:
  conffile:
    file: ./run/secrets/aerospike.conf
  discoveryfile:
    file: ./run/secrets/discovery.py